### ISSUE TITLE
linux-64 gsl 2.7 version: libgsl.so links to libgsl.so.25.1.0

### ISSUE THREAD

**Issue by prjemian** [conda-forge/gsl-feedstock#61]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

This is a problem in the tarball posted at https://anaconda.org/conda-forge/gsl/files.

As noted elsewhere:

- https://github.com/bluesky/libhkl/issues/20

[linux-64/gsl-2.7-he838d99_0.tar.bz2](https://anaconda.org/conda-forge/gsl/2.7/download/linux-64/gsl-2.7-he838d99_0.tar.bz2)

When the tarball is expanded (by conda install), its include file says it is version 2.7 (as expected) but the `libgsl.so` file links to `libgsl.so.25.1.0`.

These steps to reproduce (in a clean VM):

```bash
conda create -y -n test 
conda activate test
conda install -y conda-forge::gsl
grep VERSION $CONDA_PREFIX/include/gsl/*.h
ls -lAFgh $CONDA_PREFIX/lib | grep libgsl.so
```

The tarball has the incorrect content:

```bash
(gsl) root@683c40875983:/opt/conda/pkgs/gsl-2.7-he838d99_0# grep VERSION ./include/gsl/*
./include/gsl/gsl_complex.h:     defined(__STDC_VERSION__) && (__STDC_VERSION__ >= 201112L) /* C11 */
./include/gsl/gsl_version.h:#ifndef __GSL_VERSION_H__
./include/gsl/gsl_version.h:#define __GSL_VERSION_H__
./include/gsl/gsl_version.h:#define GSL_VERSION "2.7"
./include/gsl/gsl_version.h:#define GSL_MAJOR_VERSION 2
./include/gsl/gsl_version.h:#define GSL_MINOR_VERSION 7
./include/gsl/gsl_version.h:#endif /* __GSL_VERSION_H__ */
(gsl) root@683c40875983:/opt/conda/pkgs/gsl-2.7-he838d99_0# ls -lAFGh ./lib/libgsl.so*
lrwxrwxrwx 1 root   16 Jul 18 19:07 ./lib/libgsl.so -> libgsl.so.25.1.0*
lrwxrwxrwx 1 root   16 Jul 18 19:07 ./lib/libgsl.so.25 -> libgsl.so.25.1.0*
-rwxr-xr-x 2 root 3.4M Jul 15  2021 ./lib/libgsl.so.25.1.0*
```

### Installed packages

```shell
(gsl) root@683c40875983:/opt/conda/pkgs/gsl-2.7-he838d99_0# conda list
# packages in environment at /opt/conda/envs/gsl:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
gsl                       2.7                  he838d99_0    conda-forge
libblas                   3.9.0           22_linux64_openblas    conda-forge
libcblas                  3.9.0           22_linux64_openblas    conda-forge
libgcc-ng                 14.1.0               h77fa898_0    conda-forge
libgfortran-ng            14.1.0               h69a702a_0    conda-forge
libgfortran5              14.1.0               hc5f4f2c_0    conda-forge
libgomp                   14.1.0               h77fa898_0    conda-forge
libopenblas               0.3.27          pthreads_hac2b453_1    conda-forge
```

### Environment info

```shell
(gsl) root@683c40875983:/opt/conda/pkgs/gsl-2.7-he838d99_0# conda info

     active environment : gsl
    active env location : /opt/conda/envs/gsl
            shell level : 2
       user config file : /root/.condarc
 populated config files : /opt/conda/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=skylake
                          __conda=24.5.0=0
                          __glibc=2.31=0
                          __linux=5.15.0=0
                          __unix=0=0
       base environment : /opt/conda  (writable)
      conda av data dir : /opt/conda/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.14 Linux/5.15.0-112-generic ubuntu/20.04.6 glibc/2.31 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```

**Comment by traversaro** [comment]
This is interesting, indeed the soversion should be `26` according to http://git.savannah.gnu.org/cgit/gsl.git/diff/configure.ac?h=release-2-7&id=659dcc296cc31532d133d5374ce1baf82f280610 . Perhaos something is going wrong when we call `autoreconf` ? I am definitely not an autotools expert, but we can look in cleaning this in https://github.com/conda-forge/gsl-feedstock/pull/60 (we can't just change the soversion of 2.7 as it would result in a ABI break for gsl 2.7).

However, while it would be interesting to understand why this is happening, this should not a be a problem in conda-forge, as you can't have multiple gsl version installed in the same conda environment, so even if two different versions have the same soversion number, I do not think it should be a problem. What kind of failure you are experiencing related to this?

**Comment by traversaro** [comment]
Just to clarify, the soversion 25 is the one of gsl 2.6 (see http://git.savannah.gnu.org/cgit/gsl.git/tree/configure.ac?h=release-2-7&id=659dcc296cc31532d133d5374ce1baf82f280610), not the one of gsl 2.5 .

**Comment by prjemian** [comment]
What happens is that my package (libhkl) fails to run its functions that require libgsl because it cannot find the expected libgsl.so.27.  And stops cold dead.

I don't know about soversion 26, this issue is about the linux-64/gsl-2.7 he838d99 tarball.  Likely it is mislabeled (which AFAIK happens during `autoreconf`).  My package works when I rename the `libgsl.so.25.0.0` file to `libgsl.so.27.0.0`.

With so many downloads of the gsl-2.7 package, it surprises me that I am first to identify this.  Double-checked to verify that my report is based on download file from anaconda.org.

**Comment by prjemian** [comment]
> stops cold dead

Actual traceback is in the _details_ dropdown of this issue comment:
https://github.com/bluesky/libhkl/issues/20#issue-2409824154

**Comment by traversaro** [comment]
> What happens is that my package (libhkl) fails to run its functions that require libgsl because it cannot find the expected libgsl.so.27. And stops cold dead.

But your software it expects `libgsl.so.27` ? If you are building it against the conda-forge's gsl 2.7.0 package, you should expect `libgsl.so.25` or whatever soversion we used. How you end up requiring .27, also considering the .27 is the soverion of 2.7.1, not of 2.7.0 .

> With so many downloads of the gsl-2.7 package, it surprises me that I am first to identify this. Double-checked to verify that my report is based on download file from anaconda.org.

Indeed, I regularly run software that links gsl 2.7, so I am surprised as well, and I suspect there is something different in your software w.r.t. to other consumers.

**Comment by prjemian** [comment]
Could be.  I'm not building with the conda-forge compilers and that might be part of the problem (that my package expects libgsl.so.27 instead of just libgsl.so).  (I'm building my package on Debian with the packages downloaded via `apt install`.)

BUT ... Ignoring my software completely,

Download the described gsl-2.7 package from conda-forge and open it up.  It contains a file `libgsl.so.25.1.0`.  That's the problem.  Here, I show the tarball downloaded from anaconda.org as opened in Window's 7-zip program:

![image](https://github.com/user-attachments/assets/3fa63e7c-abda-47db-a7ae-77d4f53093cd)

**Comment by prjemian** [comment]
Compare with linux-64/gsl-2.7.1 from the [anaconda](https://anaconda.org/anaconda/gsl/files) channel:
![image](https://github.com/user-attachments/assets/c0e6dc73-2bd0-433f-bce3-c6a13ea05028)

My package works with this one.

**Comment by prjemian** [comment]
This looks like the same situation: https://github.com/samtools/bcftools/issues/1698

**Comment by traversaro** [comment]
Ok, first I will try to do a bit of recap. 

I started looking a bit more in the soversion situation, and I think it is correct that 2.7 has the 25 soversion. Indeed, if you check in http://git.savannah.gnu.org/cgit/gsl.git/tree/configure.ac#n10, you see that the soversion is actually reset when the `GSL_AGE` is reset to 0, so for the latest releases we have the current situation:

| gsl version | libgsl version | libgsl soversion | file list in a linux distro  to verify the soversion |
|:-------:|:--------------:|:-------------:|:----------:|
| gsl-2.6   | libgsl 25:0:0 |  25          |   https://pkgs.alpinelinux.org/contents?branch=v3.12&name=gsl&arch=x86_64&repo=community |
| gsl-2.7   | libgsl 26:0:1 |  25          |  https://pkgs.alpinelinux.org/contents?branch=v3.14&name=gsl&arch=x86_64&repo=community |
| gsl-2.7.1 | libgsl 27:0:0 |  27          | https://pkgs.alpinelinux.org/contents?branch=v3.16&name=gsl&arch=x86_64&repo=community |
| gsl-2.8   | libgsl 28:0:0 |  28          | https://packages.debian.org/experimental/arm64/libgsl28/filelist |

As a reference for the soversion name I used alpine and debian, but you can check yourself in any distro by looking at https://repology.org/project/gsl/versions .

Indeed, the 2.7 case is a bit strange as the README reported that "(***) There was an error on this release. Age should have been reset to 26:0:0". So in theory the correct soversion for 2.7 should have been 26 instead of 25, but we can't change it without breaking existing packages in conda-forge built against gsl 2.7.

So, having said that, it seems to me that gsl 2.7 containing `libgsl.so.25` make sense and is aligned with the rest of linux distributions, unless I am missing something.

**Comment by traversaro** [comment]
> Could be. I'm not building with the conda-forge compilers and that might be part of the problem (that my package expects libgsl.so.27 instead of just libgsl.so). (I'm building my package on Debian with the packages downloaded via `apt install`.)

Probably I am missing something on this, but how does that work? If you are building a library against gsl 2.7.1 in debian, why it should work when you install gsl 2.7 (not 2.7.1) from conda-forge? And even if you use exactly the same version of the dependencies, there is nothing that ensures (or promises) that the ABI between the Debian-built library and the conda-forge-built library is the same.

Just to understand, why don't you simply build the package from source in https://github.com/conda-forge/hkl-feedstock/blob/main/recipe/build.sh from the conda-forge dependencies instead of doing a binary repackaging of binaries built on Debian against debian provided dependencies?

**Comment by traversaro** [comment]
> This looks like the same situation: [samtools/bcftools#1698](https://github.com/samtools/bcftools/issues/1698)

I am not sure that is related, it is not even clear if they refer to a conda package or not.

**Comment by prjemian** [comment]
Your table is very helpful to understand that the version (and soversion) numbers of gsl and libgsl are not identical.

There are plans to refactor the hkl-feedstock in a future release to use the conda-forge compilers.

Thanks for your assistance.
